# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EqDistantDockWidget
                                 A QGIS plugin
 Plugin to generate median line using Equidistant method
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-11
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Ivan Busthomi
        email                : ivanbusthomi@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from qgis.PyQt.QtCore import QVariant, pyqtSlot
from qgis.core import *
from qgis.utils import iface
from qgis.gui import QgsMessageBar
import time, processing

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'eq_distant_dockwidget_base.ui'))


class EqDistantDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    """DockWidget UI Implementation
    """
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(EqDistantDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.input_mode = ""
        self.btn_preprocess.setEnabled(False)
        self.btn_process.setEnabled(False)
        self.outputGroup.setEnabled(False)

    def closeEvent(self, event):
        """Close Event.
        """
        self.closingPlugin.emit()
        event.accept()
